name: Conan 2 CI

on:
  push:
    branches:
      - master

jobs:
  conan_build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Restore Conan cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan
          ~/.conan2
        key: conan-cache-${{ runner.os }}
        restore-keys: conan-cache-${{ runner.os }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3-pip

    - name: Install Conan
      run: sudo pip3 install conan==1.59.0
 
    - name: Build and test package v4.1.1
      run: conan create . 4.1.1@ -s build_type=Debug -s compiler.cppstd=17 --build missing

    - name: Save Conan cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan
          ~/.conan2
        key: conan-cache-${{ runner.os }}
        restore-keys: conan-cache-${{ runner.os }}
